//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBESearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyItemCode
    {
        public int CompanyID { get; set; }
        public int ItemCode { get; set; }
        public string Comments { get; set; }
    
        public virtual DBECompany DBECompany { get; set; }
        public virtual ItemCode ItemCode1 { get; set; }
    }
}
