//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBESearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBECompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBECompany()
        {
            this.CompanyItemCodes = new HashSet<CompanyItemCode>();
            this.CompanyNAICSCodes = new HashSet<CompanyNAICSCode>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string DBAName { get; set; }
        public string OwnersFirstName { get; set; }
        public string OwnersLastName { get; set; }
        public string CompanyAddress { get; set; }
        public string Email { get; set; }
        public string AltEmail { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string AltFax { get; set; }
        public string District { get; set; }
        public Nullable<bool> DBE { get; set; }
        public Nullable<bool> ACDBE { get; set; }
        public Nullable<bool> SBP { get; set; }
        public Nullable<bool> MBE { get; set; }
        public Nullable<bool> Certified { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public Nullable<System.DateTime> DecertificationDate { get; set; }
        public string DecertReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyItemCode> CompanyItemCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyNAICSCode> CompanyNAICSCodes { get; set; }
    }
}
