//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBESearch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBESearchDirectoryEntities : DbContext
    {
        public DBESearchDirectoryEntities()
            : base("name=DBESearchDirectoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyItemCode> CompanyItemCodes { get; set; }
        public virtual DbSet<CompanyNAICSCode> CompanyNAICSCodes { get; set; }
        public virtual DbSet<DBECompany> DBECompanies { get; set; }
        public virtual DbSet<ItemCode> ItemCodes { get; set; }
        public virtual DbSet<NAICSCode> NAICSCodes { get; set; }
    }
}
